Repository blossomlabsio/Bloom-Backend, pull requests merged in 2023-10, with the labels that each got.

#21 [chore]: Refactor the project
  alembic.ini
  alembic/README
  alembic/env.py
  alembic/versions/0902da57a42d_changed_the_default_values_of_some_.py
  alembic/versions/12e8f89228a5_change_default_field.py
  alembic/versions/3d7cc643c9dd_testing_changes.py
  alembic/versions/5808f43c1708_db_init.py
  alembic/versions/6bf2d73c7f2c_added_db.py
  alembic/versions/83b1f4c7bbec_changed_the_default_values_of_some_.py
  alembic/versions/84350086e09e_removed_is_active_from_db_model.py
  alembic/versions/c2b5ba78e943_changed_the_default_values_of_some_.py
  alembic/versions/d07fb699344b_changed_the_default_values_of_some_.py
  bloom/api.py
  bloom/api/router/__init__.py
  bloom/api/router/auth/__init__.py
  bloom/api/router/auth/auth_router.py
  bloom/api/router/status/__init__.py
  bloom/api/router/status/status_router.py
  bloom/api/router/users/__init__.py
  bloom/app.py
  bloom/auth/__init__.py
  bloom/auth/endpoints.py
  bloom/auth/schemas.py
  bloom/config.py
  bloom/core/settings/__init__.py
  bloom/db/migrations/__init__.py
  bloom/db/queries/__init__.py
  bloom/db/queries/user_model_queries.py
  bloom/db/repositories/__init__.py
  bloom/jwt/__init__.py
  bloom/jwt/auth_handler.py
  bloom/jwt/schemas.py
  bloom/jwt/token_handler.py
  bloom/logging.py
  bloom/main.py
  bloom/models/domain/__init__.py
  bloom/models/schemas/__init__.py
  bloom/models/user.py
  bloom/postgres.py
  bloom/security.py
  bloom/services/__init__.py
  bloom/services/jwt/__init__.py
  bloom/user/__init__.py
  bloom/user/endpoints.py
  bloom/user/schemas.py
Labels: hacktoberfest

#31 Add pyenv compatibility and fix README.md
  .python-version
  README.md
Labels: documentation, hacktoberfest

#34 Fix: Add bcrypt as a dependency to resolve MissingBackendError #33
  pdm.lock
  pyproject.toml
Labels: bug, hacktoberfest

#37 Fix pre-commit checks failure
  bloom/app.py
  bloom/auth/endpoints.py
  bloom/jwt/auth_handler.py
  bloom/security.py
Labels: bug, hacktoberfest
